export default {
  baseStyle: {
    color: {
      light: "neutral.900",
      dark: "neutral.100",
    },
  },
  variants: {
    h1: {
      fontFamily: "Poppins-SemiBold",
      fontWeight: "600",
      fontSize: 34,
      lineHeight: 42,
    },
    h2: {
      fontFamily: "Poppins-SemiBold",
      fontWeight: "600",
      fontSize: 28,
      lineHeight: 36,
    },
    h3: {
      fontFamily: "Poppins-SemiBold",
      fontWeight: "600",
      fontSize: 22,
      lineHeight: 30,
    },
    h4: {
      fontFamily: "Poppins-SemiBold",
      fontWeight: "600",
      fontSize: 20,
      lineHeight: 28,
    },
    h5: {
      fontFamily: "Poppins-SemiBold",
      fontWeight: "600",
      fontSize: 18,
      lineHeight: 26,
    },
    h6: {
      fontFamily: "Poppins-SemiBold",
      fontWeight: "600",
      fontSize: 16,
      lineHeight: 24,
    },
    p1: {
      fontFamily: "Poppins-Regular",
      fontWeight: "400",
      fontSize: 20,
      lineHeight: 28,
    },
    p2: {
      fontFamily: "Poppins-Regular",
      fontWeight: "400",
      fontSize: 18,
      lineHeight: 26,
    },
    p3: {
      fontFamily: "Poppins-Regular",
      fontWeight: "400",
      fontSize: 16,
      lineHeight: 24,
    },
    p4: {
      fontFamily: "Poppins-Regular",
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 22,
    },
    caption: {
      fontFamily: "Poppins-Regular",
      fontWeight: "400",
      fontSize: 12,
      lineHeight: 20,
    },
    input: {
      fontFamily: "Poppins-Regular",
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 22,
    },
    label: {
      fontFamily: "Poppins-Medium",
      fontWeight: "500",
      fontSize: 16,
      lineHeight: 24,
    },
    btn1: {
      fontFamily: "Poppins-Medium",
      fontWeight: "500",
      fontSize: 18,
      lineHeight: 26,
      color: "neutral.100",
    },
    btn2: {
      fontFamily: "Poppins-Medium",
      fontWeight: "500",
      fontSize: 16,
      lineHeight: 24,
      color: "neutral.100",
    },
    btn3: {
      fontFamily: "Poppins-Medium",
      fontWeight: "500",
      fontSize: 14,
      lineHeight: 22,
      color: "neutral.100",
    },
    btn4: {
      fontFamily: "Poppins-Medium",
      fontWeight: "500",
      fontSize: 12,
      lineHeight: 20,
      color: "neutral.100",
    },
    btn5: {
      fontFamily: "Poppins-Medium",
      fontWeight: "500",
      fontSize: 10,
      lineHeight: 18,
      color: "neutral.100",
    },
  },
  defaults: {
    variant: "p3",
  },
};
